#!/bin/bash
shopt -s globstar
set -e

rm -rf /srv/pajaro/*

for f in `find . -name "*.md"`; do
  if [[ ${f##*/} == "README.md" ]]; then
    pandoc -s $f -t html5 -o ${f/%.md/.html}
  else
    pandoc -s $f -t revealjs -o ${f/%.md/.html} -V revealjs-url=https://unpkg.com/reveal.js/ -V theme=dracula --include-in-header=estilos.css
  fi
done

cp *.html --parents /srv/pajaro
cp -r images  --parents /srv/pajaro/
